{{- if .Values.isOpenshift -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: redis-enterprise-scc-v2
  annotations:
    kubernetes.io/description: redis-enterprise-scc is the minimal SCC needed to run Redis Enterprise nodes on Kubernetes.
      It provides the same features as restricted-v2 SCC, but allows pods to enable the SYS_RESOURCE capability,
      which is required by Redis Enterprise nodes to manage file descriptor limits and OOM scores for database shards.
      Additionally, it requires pods to run as UID/GID 1001, which are the UID/GID used within the Redis Enterprise node containers.
allowedCapabilities:
- SYS_RESOURCE
allowHostDirVolumePlugin: false
allowHostIPC : false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAs
  uid: 1001
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1001
    max: 1001
seLinuxContext:
  type: MustRunAs
seccompProfiles:
- runtime/default
supplementalGroups:
  type: RunAsAny
{{- end -}}
